### ISSUE TITLE
4. Editor - Generation and Download

### ISSUE THREAD

**Issue by ines29** [OMM-33/mememuc#5]
By default the generated meme should be added to the website. Additionally the creator receives 
immediate feedback.
Basic: The finished meme is generated and shown to the user.
Intermediate: The user can choose to either create the meme locally on their device or on the 
webserver. Afterwards they are shown the image and provided with a download button.
Advanced: In addition to intermediate, the user can specify a target file-size before the image 
creating and share buttons are presented below the image. The generated meme should have the 
specified (or lower) file-size. Providing a button that copies the “singleview-URL” of the image into 
the clipboard suffices as a share button.

- [x] generate and show
- [x] generate local or server and show or download
- [x] generate with file-size and download and share

**Comment by Muhlex** [comment]
"Generate Server" (lol) hier ist doch ein riesen Aufwand für uns, wo wir entschieden haben, das Rendern clientside zu machen? Also weiß hier jemand ob das wirklich dazu gehört oder ob ein Download Button nicht reicht (und die Option, das Meme im Profil zu speichern oder eben nicht)?
